//! Fullscreen pass: GTAO ambient occlusion production stage.
//!
//! Reads the view-space depth mip chain generated by `gtao_prefilter_*` plus the smooth
//! view-space normal prepass, evaluates the slice/step horizon search, and writes the packed
//! AO working term plus denoise edges.

#import renderide::core::fullscreen as fs
#import renderide::post::gtao_filter as gf
#import renderide::frame::types as ft
#import renderide::post::gtao_params as gparams

const PI: f32 = 3.14159265359;
const PI_HALF: f32 = 1.57079632679;
const HILBERT_WIDTH: u32 = 64u;
const HILBERT_INDEX_FRAME_OFFSET: u32 = 288u;
const MIN_VISIBILITY: f32 = 0.03;
#ifdef MULTIVIEW
@group(0) @binding(0) var view_depth: texture_2d_array<f32>;
@group(0) @binding(1) var view_normals: texture_2d_array<f32>;
#else
@group(0) @binding(0) var view_depth: texture_2d<f32>;
@group(0) @binding(1) var view_normals: texture_2d<f32>;
#endif

@group(0) @binding(2) var<uniform> frame: ft::FrameGlobals;

@group(0) @binding(3) var<uniform> gtao: gparams::GtaoParams;

struct GtaoMainOutput {
    @location(0) ao_term: vec4<f32>,
    @location(1) edges: vec4<f32>,
}

struct GtaoSampleOutput {
    visibility: f32,
    edges_lrtb: vec4<f32>,
}

@vertex
fn vs_main(@builtin(vertex_index) vid: u32) -> fs::FullscreenVertexOutput {
    return fs::vertex_main(vid);
}

fn proj_params_for_view(view_layer: u32) -> vec4<f32> {
    if (view_layer == 0u) {
        return frame.proj_params_left;
    }
    return frame.proj_params_right;
}

fn projection_flags_for_view(view_layer: u32) -> u32 {
    if (view_layer == 0u) {
        return frame.frame_tail.y;
    }
    return frame.frame_tail.z;
}

fn view_is_orthographic(view_layer: u32) -> bool {
    return (projection_flags_for_view(view_layer) & ft::FRAME_PROJECTION_FLAG_ORTHOGRAPHIC) != 0u;
}

fn view_pos_from_uv(
    uv: vec2<f32>,
    view_z: f32,
    proj_params: vec4<f32>,
    view_layer: u32,
) -> vec3<f32> {
    let ndc_xy = vec2<f32>(uv.x * 2.0 - 1.0, 1.0 - uv.y * 2.0);
    if (view_is_orthographic(view_layer)) {
        let view_x = (ndc_xy.x + proj_params.z) / max(abs(proj_params.x), 1e-6);
        let view_y = (ndc_xy.y + proj_params.w) / max(abs(proj_params.y), 1e-6);
        return vec3<f32>(view_x, view_y, view_z);
    }
    let view_x = (ndc_xy.x + proj_params.z) * view_z / proj_params.x;
    let view_y = (ndc_xy.y + proj_params.w) * view_z / proj_params.y;
    return vec3<f32>(view_x, view_y, view_z);
}

fn mip_dimensions(mip: u32) -> vec2<u32> {
#ifdef MULTIVIEW
    let dim = textureDimensions(view_depth, i32(mip));
#else
    let dim = textureDimensions(view_depth, i32(mip));
#endif
    return vec2<u32>(dim.xy);
}

fn load_view_z(pix: vec2<i32>, view_layer: u32, mip: u32) -> f32 {
    let dim = mip_dimensions(mip);
    let max_pix = vec2<i32>(i32(dim.x) - 1, i32(dim.y) - 1);
    let p = clamp(pix, vec2<i32>(0), max_pix);
#ifdef MULTIVIEW
    return textureLoad(view_depth, p, i32(view_layer), i32(mip)).r;
#else
    return textureLoad(view_depth, p, i32(mip)).r;
#endif
}

fn load_view_z_uv(uv: vec2<f32>, view_layer: u32, mip: u32) -> f32 {
    let dim = mip_dimensions(mip);
    let pix = vec2<i32>(uv * vec2<f32>(dim));
    return load_view_z(pix, view_layer, mip);
}

fn normal_dimensions() -> vec2<u32> {
#ifdef MULTIVIEW
    let dim = textureDimensions(view_normals);
#else
    let dim = textureDimensions(view_normals);
#endif
    return vec2<u32>(dim.xy);
}

fn load_prepass_view_normal(pix: vec2<i32>, view_layer: u32) -> vec4<f32> {
    let dim = normal_dimensions();
    let max_pix = vec2<i32>(i32(dim.x) - 1, i32(dim.y) - 1);
    let p = clamp(pix, vec2<i32>(0), max_pix);
#ifdef MULTIVIEW
    return textureLoad(view_normals, p, i32(view_layer), 0);
#else
    return textureLoad(view_normals, p, 0);
#endif
}

fn calculate_view_normal(
    edges_lrtb: vec4<f32>,
    center: vec3<f32>,
    left: vec3<f32>,
    right: vec3<f32>,
    top: vec3<f32>,
    bottom: vec3<f32>,
) -> vec3<f32> {
    let accepted = clamp(
        vec4<f32>(
            edges_lrtb.x * edges_lrtb.z,
            edges_lrtb.z * edges_lrtb.y,
            edges_lrtb.y * edges_lrtb.w,
            edges_lrtb.w * edges_lrtb.x,
        ) + vec4<f32>(0.01),
        vec4<f32>(0.0),
        vec4<f32>(1.0),
    );

    let l = normalize(left - center);
    let r = normalize(right - center);
    let t = normalize(top - center);
    let b = normalize(bottom - center);
    let n = accepted.x * cross(l, t)
        + accepted.y * cross(t, r)
        + accepted.z * cross(r, b)
        + accepted.w * cross(b, l);
    let n_len = length(n);
    if (n_len < 1e-5) {
        return vec3<f32>(0.0, 0.0, -1.0);
    }
    return n / n_len;
}

fn reconstruct_view_normal(
    uv: vec2<f32>,
    proj_params: vec4<f32>,
    z_center: f32,
    z_left: f32,
    z_right: f32,
    z_top: f32,
    z_bottom: f32,
    edges_lrtb: vec4<f32>,
    view_layer: u32,
) -> vec3<f32> {
    let inv_viewport = 1.0 / vec2<f32>(f32(frame.viewport_width), f32(frame.viewport_height));
    let center = view_pos_from_uv(uv, z_center, proj_params, view_layer);
    let left = view_pos_from_uv(uv + vec2<f32>(-inv_viewport.x, 0.0), z_left, proj_params, view_layer);
    let right = view_pos_from_uv(uv + vec2<f32>(inv_viewport.x, 0.0), z_right, proj_params, view_layer);
    let top = view_pos_from_uv(uv + vec2<f32>(0.0, -inv_viewport.y), z_top, proj_params, view_layer);
    let bottom = view_pos_from_uv(uv + vec2<f32>(0.0, inv_viewport.y), z_bottom, proj_params, view_layer);
    return calculate_view_normal(edges_lrtb, center, left, right, top, bottom);
}

fn select_view_normal(
    pix: vec2<i32>,
    view_layer: u32,
    uv: vec2<f32>,
    proj_params: vec4<f32>,
    z_center: f32,
    z_left: f32,
    z_right: f32,
    z_top: f32,
    z_bottom: f32,
    edges_lrtb: vec4<f32>,
) -> vec3<f32> {
    let prepass = load_prepass_view_normal(pix, view_layer);
    let prepass_len = length(prepass.xyz);
    if (prepass.a > 0.5 && prepass_len > 1e-4) {
        return prepass.xyz / prepass_len;
    }
    return reconstruct_view_normal(
        uv,
        proj_params,
        z_center,
        z_left,
        z_right,
        z_top,
        z_bottom,
        edges_lrtb,
        view_layer,
    );
}

fn hilbert_index(pos_x_in: u32, pos_y_in: u32) -> u32 {
    var pos_x = pos_x_in & (HILBERT_WIDTH - 1u);
    var pos_y = pos_y_in & (HILBERT_WIDTH - 1u);
    var index = 0u;
    var cur_level = HILBERT_WIDTH / 2u;
    loop {
        if (cur_level == 0u) {
            break;
        }
        let region_x = select(0u, 1u, (pos_x & cur_level) > 0u);
        let region_y = select(0u, 1u, (pos_y & cur_level) > 0u);
        index = index + cur_level * cur_level * ((3u * region_x) ^ region_y);
        if (region_y == 0u) {
            if (region_x == 1u) {
                pos_x = (HILBERT_WIDTH - 1u) - pos_x;
                pos_y = (HILBERT_WIDTH - 1u) - pos_y;
            }
            let temp = pos_x;
            pos_x = pos_y;
            pos_y = temp;
        }
        cur_level = cur_level / 2u;
    }
    return index;
}

fn spatio_temporal_noise(pix: vec2<i32>, frame_index: u32) -> vec2<f32> {
    var index = hilbert_index(u32(pix.x), u32(pix.y));
    index = index + HILBERT_INDEX_FRAME_OFFSET * (frame_index % 64u);
    return fract(
        vec2<f32>(0.5)
            + f32(index) * vec2<f32>(0.75487766624669276005, 0.56984029099805326591),
    );
}

fn multi_bounce_fit(ao: f32, albedo: f32) -> f32 {
    let a = 2.0404 * albedo - 0.3324;
    let b = 4.7951 * albedo - 0.6417;
    let c = 2.7552 * albedo + 0.6903;
    return max(ao, ((a * ao - b) * ao + c) * ao);
}

fn sample_mip_for_offset(sample_offset_length: f32) -> u32 {
    let max_mip = f32(max(gtao.view_depth_mip_count, 1u) - 1u);
    let mip = clamp(
        floor(log2(max(sample_offset_length, 1.0)) - gtao.depth_mip_sampling_offset),
        0.0,
        max_mip,
    );
    return u32(mip);
}

fn add_horizon_sample(
    sample_uv: vec2<f32>,
    view_layer: u32,
    mip: u32,
    view_pos: vec3<f32>,
    view_dir: vec3<f32>,
    proj_params: vec4<f32>,
    low_horizon_cos: f32,
    falloff_mul: f32,
    falloff_add: f32,
) -> f32 {
    let sample_z = load_view_z_uv(sample_uv, view_layer, mip);
    if (sample_z <= 0.0) {
        return low_horizon_cos;
    }

    let sample_pos = view_pos_from_uv(sample_uv, sample_z, proj_params, view_layer);
    let delta = sample_pos - view_pos;
    let dist = length(delta);
    if (dist <= 1e-4) {
        return low_horizon_cos;
    }

    let falloff_base = length(vec3<f32>(
        delta.x,
        delta.y,
        delta.z * (1.0 + gtao.thin_occluder_compensation),
    ));
    let weight = clamp(falloff_base * falloff_mul + falloff_add, 0.0, 1.0);
    let candidate = dot(delta / dist, view_dir);
    return mix(low_horizon_cos, candidate, weight);
}

fn compute_gtao(pix: vec2<i32>, uv: vec2<f32>, view_layer: u32) -> GtaoSampleOutput {
    let viewport = vec2<f32>(f32(frame.viewport_width), f32(frame.viewport_height));
    let inv_viewport = 1.0 / viewport;
    let proj_params = proj_params_for_view(view_layer);

    let z_center = load_view_z(pix, view_layer, 0u);
    let z_left = load_view_z(pix + vec2<i32>(-1, 0), view_layer, 0u);
    let z_right = load_view_z(pix + vec2<i32>(1, 0), view_layer, 0u);
    let z_top = load_view_z(pix + vec2<i32>(0, -1), view_layer, 0u);
    let z_bottom = load_view_z(pix + vec2<i32>(0, 1), view_layer, 0u);
    let edges_lrtb = gf::gtao_calculate_edges(z_center, z_left, z_right, z_top, z_bottom);

    if (z_center <= 0.0 || gtao.radius_world <= 0.0 || gtao.intensity <= 0.0) {
        return GtaoSampleOutput(1.0, edges_lrtb);
    }

    let view_normal = select_view_normal(
        pix,
        view_layer,
        uv,
        proj_params,
        z_center,
        z_left,
        z_right,
        z_top,
        z_bottom,
        edges_lrtb,
    );

    let biased_z = z_center * 0.99999;
    let view_pos = view_pos_from_uv(uv, biased_z, proj_params, view_layer);
    let orthographic = view_is_orthographic(view_layer);
    let view_dir = select(normalize(-view_pos), vec3<f32>(0.0, 0.0, -1.0), orthographic);
    let effect_radius = max(gtao.radius_world * gtao.radius_multiplier, 1e-4);
    let perspective_pixel_view_size = biased_z * 2.0 / max(abs(proj_params.x) * viewport.x, 1e-4);
    let orthographic_pixel_view_size = 2.0 / max(abs(proj_params.x) * viewport.x, 1e-4);
    let pixel_view_size = max(select(
        perspective_pixel_view_size,
        orthographic_pixel_view_size,
        orthographic,
    ), 1e-6);
    let screenspace_radius = min(gtao.max_pixel_radius, effect_radius / pixel_view_size);

    var visibility = clamp((10.0 - screenspace_radius) / 100.0, 0.0, 1.0) * 0.5;
    let pixel_too_close_threshold = 1.3;
    let min_s = pixel_too_close_threshold / max(screenspace_radius, 1e-4);

    let falloff_fraction = clamp(gtao.falloff_range, 0.05, 1.0);
    let falloff_range = max(falloff_fraction * effect_radius, 1e-4);
    let falloff_from = effect_radius * (1.0 - falloff_fraction);
    let falloff_mul = -1.0 / falloff_range;
    let falloff_add = falloff_from / falloff_range + 1.0;

    let slice_count = max(gtao.slice_count, 1u);
    let steps_per_slice = max(gtao.steps_per_slice, 1u);
    let noise = spatio_temporal_noise(pix, frame.frame_tail.x);

    for (var slice: u32 = 0u; slice < slice_count; slice = slice + 1u) {
        let slice_k = (f32(slice) + noise.x) / f32(slice_count);
        let phi = slice_k * PI;
        let cos_phi = cos(phi);
        let sin_phi = sin(phi);
        let direction_vec = vec3<f32>(cos_phi, sin_phi, 0.0);
        let ortho_direction_vec = direction_vec - dot(direction_vec, view_dir) * view_dir;
        let axis_raw = cross(ortho_direction_vec, view_dir);
        let axis_len = length(axis_raw);
        if (axis_len < 1e-6) {
            continue;
        }
        let axis_vec = axis_raw / axis_len;
        var projected_normal_vec = view_normal - axis_vec * dot(view_normal, axis_vec);
        var projected_normal_vec_length = length(projected_normal_vec);
        if (projected_normal_vec_length < 1e-6) {
            continue;
        }

        let sign_norm = sign(dot(ortho_direction_vec, projected_normal_vec));
        let cos_norm = clamp(dot(projected_normal_vec, view_dir) / projected_normal_vec_length, 0.0, 1.0);
        let n = sign_norm * acos(cos_norm);
        let sin_n = sin(n);
        let low_horizon_cos0 = cos(n + PI_HALF);
        let low_horizon_cos1 = cos(n - PI_HALF);
        var horizon_cos0 = low_horizon_cos0;
        var horizon_cos1 = low_horizon_cos1;

        let omega = vec2<f32>(cos_phi, -sin_phi) * screenspace_radius;
        for (var step: u32 = 0u; step < steps_per_slice; step = step + 1u) {
            let step_base_noise = (f32(slice) + f32(step) * f32(steps_per_slice)) * 0.6180339887498948482;
            let step_noise = fract(noise.y + step_base_noise);
            var s = (f32(step) + step_noise) / f32(steps_per_slice);
            s = pow(s, gtao.sample_distribution_power);
            s = s + min_s;

            let sample_offset_pixels = s * omega;
            let sample_offset_length = length(sample_offset_pixels);
            let mip = sample_mip_for_offset(sample_offset_length);
            let sample_offset_uv = round(sample_offset_pixels) * inv_viewport;

            let shc0 = add_horizon_sample(
                uv + sample_offset_uv,
                view_layer,
                mip,
                view_pos,
                view_dir,
                proj_params,
                low_horizon_cos0,
                falloff_mul,
                falloff_add,
            );
            let shc1 = add_horizon_sample(
                uv - sample_offset_uv,
                view_layer,
                mip,
                view_pos,
                view_dir,
                proj_params,
                low_horizon_cos1,
                falloff_mul,
                falloff_add,
            );
            horizon_cos0 = max(horizon_cos0, shc0);
            horizon_cos1 = max(horizon_cos1, shc1);
        }

        projected_normal_vec_length = mix(projected_normal_vec_length, 1.0, 0.05);
        let h0 = -acos(clamp(horizon_cos1, -1.0, 1.0));
        let h1 = acos(clamp(horizon_cos0, -1.0, 1.0));
        let iarc0 = (cos_norm + 2.0 * h0 * sin_n - cos(2.0 * h0 - n)) * 0.25;
        let iarc1 = (cos_norm + 2.0 * h1 * sin_n - cos(2.0 * h1 - n)) * 0.25;
        visibility = visibility + projected_normal_vec_length * (iarc0 + iarc1);
    }

    visibility = visibility / f32(slice_count);
    visibility = pow(clamp(visibility, 0.0, 1.0), gtao.final_value_power);
    visibility = pow(clamp(visibility, 0.0, 1.0), gtao.intensity);
    visibility = max(MIN_VISIBILITY, visibility);
    return GtaoSampleOutput(
        multi_bounce_fit(visibility, gtao.albedo_multibounce),
        edges_lrtb,
    );
}

fn pack_main_output(s: GtaoSampleOutput) -> GtaoMainOutput {
    let scaled = clamp(s.visibility / gf::GTAO_OCCLUSION_TERM_SCALE, 0.0, 1.0);
    let packed = gf::gtao_pack_edges(s.edges_lrtb);
    return GtaoMainOutput(
        vec4<f32>(scaled, 0.0, 0.0, 1.0),
        vec4<f32>(packed, 0.0, 0.0, 1.0),
    );
}

#ifdef MULTIVIEW
@fragment
fn fs_main(in: fs::FullscreenVertexOutput, @builtin(view_index) view: u32) -> GtaoMainOutput {
    let pix = vec2<i32>(in.clip_pos.xy);
    return pack_main_output(compute_gtao(pix, in.uv, view));
}
#else
@fragment
fn fs_main(in: fs::FullscreenVertexOutput) -> GtaoMainOutput {
    let pix = vec2<i32>(in.clip_pos.xy);
    return pack_main_output(compute_gtao(pix, in.uv, 0u));
}
#endif
