//! Renderide renderer process entry points.
//!
//! The supported external API intentionally stays small: [`run`] starts the renderer process,
//! [`RunExit`] reports normal process exits, [`RunError`] reports fatal startup failures, and
//! [`ensure_native_stdio_forwarded_to_logger`] supports alternate entry points that initialize
//! logging themselves.
//!
//! Host/renderer wire types live in the separate `renderide-shared` crate. Renderer subsystems
//! such as IPC, scene mirroring, GPU resources, materials, and the render graph are implementation
//! details of this process crate.

mod process_io;
mod run_error;

pub(crate) use process_io::fatal_crash_log;
pub(crate) use process_io::native_stdio;

mod app;
mod assets;
mod backend;
mod color_space;
mod concurrency;
mod config;
mod cpu_parallelism;
mod diagnostics;
mod frontend;
mod gpu;
mod gpu_resource;
mod graph_inputs;

pub(crate) use gpu::present;

/// Compatibility facade over the runtime shader package generated by `build.rs`.
#[doc(hidden)]
pub(crate) mod embedded_shaders {
    include!(concat!(env!("OUT_DIR"), "/embedded_shaders.rs"));
}

mod camera;
mod ipc;
mod mesh_deform;
mod occlusion;
mod particles;
mod passes;
mod reflection_probes;
mod skybox;
pub(crate) use ipc::connection;
mod gpu_pools;
mod materials;
mod profiling;
mod render_graph;
mod render_phase;
mod runtime;
mod scene;
mod shader_package;
mod shared;
mod world_mesh;
mod xr;

pub use app::RunExit;
pub use run_error::RunError;

/// Forwards native stdout/stderr into the active file logger after [`logger`] initialization.
///
/// Idempotent. The main [`run`] path installs this after logging starts; entry points that skip
/// [`run`] should call this after [`logger::init_for`] or [`logger::init`].
pub fn ensure_native_stdio_forwarded_to_logger() {
    native_stdio::ensure_stdio_forwarded_to_logger();
}

/// Runs the renderer process: logging, optional IPC, app driver, and wgpu presentation.
///
/// Returns [`Ok`] for normal windowed/headless exits and [`Err`] for fatal startup failures
/// (logging, IPC, event loop creation, and similar).
pub fn run() -> Result<RunExit, RunError> {
    app::run()
}
