using System.Text.RegularExpressions;
using SharedTypeGenerator.Analysis;
using SharedTypeGenerator.IR;

namespace SharedTypeGenerator.Emission;

internal sealed partial class RustEmitter
{
    /// <summary>
    /// Writes the generated file header: generated notice, a workspace-lint <c>#![allow(...)]</c>
    /// block (generated IPC code can't reasonably satisfy discipline / style / narrowing-cast lints
    /// that apply to hand-written code), a minimal <c>glam</c> import list, and shared imports.
    /// </summary>
    private void EmitHeader(List<TypeDescriptor> types)
    {
        _w.Comment("This file is automatically generated by SharedTypeGenerator. Please do not modify this file.");
        _w.Comment($"Generated for {_engineVersion}\n");
        _w.Line("#![allow(");
        _w.Line("    missing_docs,");
        _w.Line("    variant_size_differences,");
        _w.Line("    clippy::allow_attributes,");
        _w.Line("    clippy::large_enum_variant,");
        _w.Line("    clippy::too_many_lines,");
        _w.Line("    clippy::unreadable_literal,");
        _w.Line("    clippy::explicit_iter_loop,");
        _w.Line("    clippy::match_wildcard_for_single_variants,");
        _w.Line("    clippy::manual_let_else,");
        _w.Line("    clippy::unnested_or_patterns,");
        _w.Line("    clippy::empty_structs_with_brackets,");
        _w.Line("    clippy::branches_sharing_code,");
        _w.Line("    reason = \"generated code: lints enforced on hand-written code do not apply here\"");
        _w.Line(")]");
        _w.BlankLine();
        if (NeedsCowImport(types))
            _w.Line("use std::borrow::Cow;");
        string glamList = FormatGlamUseList(types);
        if (!string.IsNullOrEmpty(glamList))
            _w.Line($"use glam::{{{glamList}}};");
        _w.Line("use super::packing::memory_packable::MemoryPackable;");
        _w.Line("use super::packing::memory_packer::MemoryPacker;");
        _w.Line("use super::packing::memory_unpacker::MemoryUnpacker;");
        _w.Line("use super::packing::memory_packer_entity_pool::MemoryPackerEntityPool;");
        _w.Line("use super::packing::polymorphic_memory_packable_entity::PolymorphicEncode;");
        _w.Line("use super::packing::polymorphic_decode_error::PolymorphicDecodeError;");
        _w.Line("use super::packing::wire_decode_error::WireDecodeError;");
        _w.Line("use super::buffer::SharedMemoryBufferDescriptor;");
        _w.Line("use super::packing::enum_repr::EnumRepr;");
        _w.Line("use bytemuck::{Pod, Zeroable};");
        _w.Line("use logger::trace;");
        _w.BlankLine();
    }

    /// <summary>Returns true when any generated field stores a borrowed-or-owned static string.</summary>
    private static bool NeedsCowImport(List<TypeDescriptor> types) =>
        types.Any(t => t.Fields.Any(f => RustFieldTypeOverrides.IsStaticStringCowOption(f.RustType)));

    /// <summary>Comma-separated <c>glam</c> identifiers for <c>use glam::{{ ... }};</c>, stable order.</summary>
    private static string FormatGlamUseList(List<TypeDescriptor> types)
    {
        List<string> names = CollectRequiredGlamTypeNames(types);
        if (names.Count == 0)
            return string.Empty;
        return string.Join(", ", names);
    }

    /// <summary>Collects which <c>glam::*</c> primitive names appear in field and polymorphic payload Rust type strings.</summary>
    private static List<string> CollectRequiredGlamTypeNames(List<TypeDescriptor> types)
    {
        var set = new HashSet<string>();
        foreach (TypeDescriptor t in types)
        {
            foreach (FieldDescriptor f in t.Fields)
                AddGlamTokensFromRustType(f.RustType, set);

            if (t.Variants != null)
            {
                foreach (PolymorphicVariant v in t.Variants)
                    AddGlamTokensFromRustType(v.CSharpName.HumanizeType(), set);
            }
        }

        List<string> ordered = [];
        foreach (string name in GlamImportOrder)
        {
            if (set.Contains(name))
                ordered.Add(name);
        }

        return ordered;
    }

    private static void AddGlamTokensFromRustType(string rustType, HashSet<string> set)
    {
        if (string.IsNullOrEmpty(rustType))
            return;

        foreach (string token in Regex.Split(rustType, @"[^A-Za-z0-9_]+"))
        {
            if (token.Length == 0)
                continue;
            if (GlamImportOrder.Contains(token))
                set.Add(token);
        }
    }
}
